SERVER_PORT=8080

DB_URL=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=gpfvmcluts2.gfybeca.int)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PRS6.UIO)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
DB_USERNAME=TUKUNAFUNC
DB_PASSWORD=tvkvn4fvnc
DB_DRIVER=oracle.jdbc.OracleDriver
DB_POOL_MAX_SIZE=20
DB_POOL_MIN_IDLE=5
DB_POOL_CONNECTION_TIMEOUT_MS=2000
DB_POOL_IDLE_TIMEOUT_MS=300000
DB_POOL_MAX_LIFETIME_MS=1800000

DB_APPDFM_URL=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.100.3.35)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=APPTEST)))
DB_APPDFM_USERNAME=TRX3
DB_APPDFM_PASSWORD=dfm02destrx3
DB_APPDFM_DRIVER=oracle.jdbc.OracleDriver
DB_APPDFM_POOL_MAX_SIZE=20
DB_APPDFM_POOL_MIN_IDLE=5
DB_APPDFM_POOL_CONNECTION_TIMEOUT_MS=2000
DB_APPDFM_POOL_IDLE_TIMEOUT_MS=300000
DB_APPDFM_POOL_MAX_LIFETIME_MS=1800000

EXTERNAL_HTTP_TIMEOUT_MS=30000
# NOTA: mapeos request/response por proveedor se resuelven en BD (TUKUNAFUNC.AD_MAPEO_SERVICIOS)
COD_CADENA_GEO_FYB=60
COD_CADENA_GEO_SANA=70
COD_CADENA_GEO_OKI=90
COD_CADENA_GEO_FR=70

# SAFETYPAY_CONFIRMATION: configuracion en BD (IN_PASARELA_WS + IN_PASARELA_WS_DEFS)
