-- Ejecutar conectado con el esquema TUKUNAFUNC antes de desplegar la aplicacion.
-- Oracle aplica COMMIT implicito para cada sentencia DDL.

CREATE SEQUENCE TUKUNAFUNC.SEQ_JEP_MERCHANT_SALES
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE
    NOORDER;

CREATE SEQUENCE TUKUNAFUNC.SEQ_DEUNA_MERCHANT_SALES
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE
    NOORDER;

-- Comprobacion sin consumir NEXTVAL.
SELECT SEQUENCE_OWNER,
       SEQUENCE_NAME,
       MIN_VALUE,
       MAX_VALUE,
       INCREMENT_BY,
       CYCLE_FLAG,
       CACHE_SIZE,
       LAST_NUMBER
  FROM ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'TUKUNAFUNC'
   AND SEQUENCE_NAME IN (
       'SEQ_JEP_MERCHANT_SALES',
       'SEQ_DEUNA_MERCHANT_SALES'
   )
 ORDER BY SEQUENCE_NAME;
